import {today,money,cents,addMonth,daysBetween,stockFor,paidFor,totalFor,dueFor,emptyState} from './domain.mjs';
import {DemoAPI,CloudAPI,loadConfig,validateConfig} from './api.mjs';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={overview:'Painel',sales:'Vendas',purchases:'Encomendas',products:'Stock',customers:'Clientes',followups:'Agenda',settings:'Definições'};
const icons={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',sales:'M3 6h18v14H3z M7 6V3h10v3 M8 12h8 M8 16h5',purchases:'M3 8l9-5 9 5v10l-9 5-9-5z M3 8l9 5 9-5 M12 13v10',products:'M4 7h16v14H4z M2 3h20v4H2z M9 12h6',customers:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M13 3a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',followups:'M4 5h16v16H4z M16 3v4 M8 3v4 M4 11h16 M8 15h3 M14 15h2',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',plus:'M12 5v14 M5 12h14',refresh:'M20 7a8 8 0 1 0 1 9 M20 3v5h-5',check:'M4 12l5 5L20 6',alert:'M12 3L2 21h20z M12 9v5 M12 17v1',wallet:'M3 5h17v16H3z M15 10h7v6h-7z',clock:'M12 8v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',arrow:'M4 12h16 M14 6l6 6-6 6'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.sales}"/></svg>`;
const badge=(text,color='')=>`<span class="badge ${color}">${esc(text)}</span>`;
const button=(text,action,id='',cls='',extra='')=>`<button class="btn ${cls}" data-action="${action}" data-id="${esc(id)}" ${extra}>${esc(text)}</button>`;
let api=null,state=emptyState(),view=paths[location.hash.slice(1)]?location.hash.slice(1):'overview',query='',filter='all',busy=false,lastSync=null,syncError='',installPrompt=null,timer=null;
let config=loadConfig();
const getProduct=id=>state.products.find(x=>x.id===id)||{name:'Produto indisponível'};
const getCustomer=id=>state.customers.find(x=>x.id===id)||{name:'Cliente indisponível'};
const dateLabel=d=>d?new Intl.DateTimeFormat('pt-PT').format(new Date(d+'T12:00:00')):'—';
const shortTime=d=>new Intl.DateTimeFormat('pt-PT',{hour:'2-digit',minute:'2-digit'}).format(d);
const matches=(...parts)=>parts.some(x=>String(x||'').toLocaleLowerCase('pt').includes(query.toLocaleLowerCase('pt')));
function notify(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function entry(error='') {
  const configured=config.supabaseUrl&&config.publishableKey;
  app.innerHTML=`<main class="entry"><section class="entry-side"><div><div class="brand"><img src="./icon.svg" alt=""><div>Fluxo Pro<small>Gestão comercial</small></div></div><h1>Do primeiro pedido<br>à próxima <em>encomenda.</em></h1><p>Encomendas, pagamentos e entregas reunidos no mesmo lugar.</p><div class="entry-steps"><span>01 · Encomendar</span><span>02 · Receber</span><span>03 · Entregar</span></div></div><div class="foot">A sua operação, sempre organizada.</div></section><section class="entry-form"><div class="entry-inner"><h2>${configured?'Entre na sua conta':'Bem-vindo ao Fluxo Pro'}</h2><p class="muted">${configured?'Use a mesma conta no computador e no telemóvel.':'Ligue a sua base de dados para começar a guardar e sincronizar os registos.'}</p>${error?`<div class="form-error" role="alert">${esc(error)}</div>`:''}${configured?`<form id="login-form"><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="username" required></div><div class="field"><label for="password">Palavra-passe</label><input id="password" name="password" type="password" autocomplete="current-password" required minlength="8"></div><div class="form-error" role="alert"></div><button class="btn primary" type="submit">Entrar</button></form><div class="connection-bar" style="margin-top:17px"><span>Ligação configurada</span><button class="link-button" data-action="connection">Alterar ligação</button></div>`:`<button class="btn primary" data-action="connection">Configurar ligação online</button><p class="help">A configuração está explicada no guia incluído no projeto.</p>`}<div class="separator">ou</div><button class="btn" data-action="demo">Experimentar demonstração</button><p class="entry-footer">A demonstração usa dados fictícios e fica apenas neste navegador.</p></div></section></main>`;
}
function shell() {
  const email=api.mode==='demo'?'Dados de exemplo':api.session?.user?.email||'Conta online';
  app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><img src="./icon.svg" alt=""><div>Fluxo Pro<small>Gestão comercial</small></div></div><nav class="nav" aria-label="Navegação principal">${Object.entries(paths).map(([k,v])=>`<a href="#${k}" class="${view===k?'active':''}" ${view===k?'aria-current="page"':''}>${icon(k)}<span>${v}</span></a>`).join('')}</nav><div class="sidebar-bottom"><div>${esc(state.settings.name)}</div><div class="small">${esc(email)}</div><button data-action="logout">${api.mode==='demo'?'Sair da demonstração':'Sair da conta'}</button></div></aside><div class="workspace"><header class="topbar"><div class="brand mobile-brand"><img src="./icon.svg" alt=""><span>${esc(state.settings.name)}</span></div><div class="right"><span class="sync ${syncError?'sync-error':''}">${api.mode==='demo'?'Demonstração local':syncError?'Ligação indisponível':lastSync?`Atualizado às ${shortTime(lastSync)}`:'A sincronizar…'}</span><button class="btn small" data-action="refresh" aria-label="Atualizar dados" title="Atualizar dados">${icon('refresh')}</button><span class="avatar" aria-hidden="true">${esc(state.settings.name[0]||'F')}</span></div></header><main class="content" id="main">${api.mode==='demo'?`<div class="mode-banner"><p><strong>Demonstração.</strong> Estes dados são fictícios e não sincronizam entre dispositivos.</p>${button('Usar conta online','logout','','small')}</div>`:''}${syncError?`<div class="mode-banner offline" role="alert"><p>${esc(syncError)}</p>${button('Tentar novamente','refresh','','small')}</div>`:''}${renderView()}</main></div></div>`;
}
function head(title,subtitle,action){return `<div class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div>${action||''}</div>`;}
function empty(title,description,action=''){return `<div class="empty">${icon('purchases')}<h3>${esc(title)}</h3><p>${esc(description)}</p>${action}</div>`;}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function toolbar(options=''){return `<div class="toolbar"><input class="search" id="search" aria-label="Pesquisar registos" type="search" placeholder="Pesquisar…" value="${esc(query)}">${options?`<select id="filter" aria-label="Filtrar registos">${options}</select>`:''}</div>`;}
const option=(value,text)=>`<option value="${value}" ${filter===value?'selected':''}>${text}</option>`;
function salesRows(rows,compact=false){return rows.map(r=>`<tr><td><strong>${esc(getCustomer(r.customer_id).name)}</strong><span class="sub">${dateLabel(r.ordered_at)}</span></td><td>${esc(getProduct(r.product_id).name)}<span class="sub">${r.quantity} ${r.quantity===1?'unidade':'unidades'}</span></td><td><strong>${money(totalFor(r))}</strong><span class="sub">${r.status==='cancelled'?'Cancelada':dueFor(state,'sale',r)>0?`${money(dueFor(state,'sale',r))} em falta`:'Pago'}</span></td><td>${badge({pending:'Por entregar',delivered:'Entregue',cancelled:'Cancelada'}[r.status],{pending:'amber',delivered:'green'}[r.status])}</td><td>${button('Ver','sale-detail',r.id,'small')}</td></tr>`);}
function followupsRows(rows){return rows.map(r=>{const days=daysBetween(today(),r.followup_at);return `<tr><td><strong>${esc(getCustomer(r.customer_id).name)}</strong><span class="sub">${esc(getCustomer(r.customer_id).phone||'Sem contacto')}</span></td><td>${esc(getProduct(r.product_id).name)}<span class="sub">Entregue ${dateLabel(r.delivered_at)}</span></td><td>${dateLabel(r.followup_at)}<span class="sub">${r.followup_done?'Concluído':days<0?`${Math.abs(days)} dias em atraso`:days===0?'Hoje':`Dentro de ${days} dias`}</span></td><td>${r.followup_done?badge('Concluído','green'):badge(days<0?'Em atraso':days<=state.settings.reminder_days?'A contactar':'Agendado',days<0?'red':days<=state.settings.reminder_days?'amber':'blue')}</td><td><div class="actions">${button('Nova venda','repeat-sale',r.id,'small')}${button(r.followup_done?'Reabrir':'Concluir','followup',r.id,'small')}</div></td></tr>`;});}
function renderView() {
  if(view==='overview'){
    const sales=state.sales.filter(r=>r.status!=='cancelled'),purchases=state.purchases.filter(r=>r.status==='open');
    const outstanding=sales.reduce((n,r)=>n+dueFor(state,'sale',r),0),received=state.payments.filter(r=>r.kind==='sale'&&r.paid_at.slice(0,7)===today().slice(0,7)).reduce((n,r)=>n+r.amount_cents,0);
    const delivered=sales.filter(r=>r.status==='delivered'&&r.delivered_at.slice(0,7)===today().slice(0,7)).reduce((n,r)=>n+totalFor(r),0);
    const low=state.products.filter(r=>r.active&&stockFor(state,r.id).available<=r.minimum);
    const follow=state.sales.filter(r=>r.status==='delivered'&&!r.followup_done&&daysBetween(today(),r.followup_at)<=state.settings.reminder_days).sort((a,b)=>a.followup_at.localeCompare(b.followup_at));
    const metric=(title,value,subtitle,i,featured='')=>`<div class="metric ${featured}"><div class="title">${title}${icon(i)}</div><strong>${value}</strong><p>${subtitle}</p></div>`;
    return `${head('Visão geral',new Intl.DateTimeFormat('pt-PT',{weekday:'long',day:'numeric',month:'long'}).format(new Date()),button('+ Nova venda','sale-form','','primary'))}<div class="metrics">${metric('Recebido este mês',money(received),'Pagamentos de clientes','wallet','featured')}${metric('Por receber',money(outstanding),`${sales.filter(r=>dueFor(state,'sale',r)>0).length} vendas com saldo em falta`,'sales')}${metric('Por entregar',sales.filter(r=>r.status==='pending').length,'Vendas com stock reservado','purchases')}${metric('A acompanhar',follow.length,'Nova encomenda após um mês','followups')}</div><div class="grid-two"><section class="panel"><div class="panel-head"><h2>A operação de hoje</h2><span class="muted small">${money(delivered)} entregues este mês</span></div><div class="panel-body"><div class="stage-grid"><div class="stage">${icon('purchases')}<b>${purchases.length}</b><span>Encomendas a chegar</span></div><div class="stage">${icon('products')}<b>${state.products.filter(r=>r.active).reduce((n,r)=>n+stockFor(state,r.id).physical,0)}</b><span>Unidades em stock</span></div><div class="stage">${icon('check')}<b>${sales.filter(r=>r.status==='delivered').length}</b><span>Vendas entregues</span></div></div></div></section><section class="panel"><div class="panel-head"><h2>Stock a repor</h2><a href="#products" class="small">Ver stock</a></div>${low.length?low.slice(0,3).map(p=>`<div class="alert-row"><div><strong>${esc(p.name)}</strong><p>${stockFor(state,p.id).available} disponíveis · mínimo ${p.minimum}</p></div>${button('Encomendar','purchase-for',p.id,'small')}</div>`).join(''):empty('Stock em dia','Os produtos estão acima do stock mínimo.')}</section></div>${follow.length?`<section class="panel" style="margin-bottom:24px"><div class="panel-head"><h2>Próximas encomendas de clientes</h2><a href="#followups" class="small">Ver agenda</a></div>${table(['Cliente','Última entrega','Voltar a contactar','Estado','Ações'],followupsRows(follow.slice(0,4)))}</section>`:''}<section class="panel"><div class="panel-head"><h2>Últimas vendas</h2><a href="#sales" class="small">Ver todas</a></div>${state.sales.length?table(['Cliente','Produto','Pagamento','Entrega',''],salesRows([...state.sales].sort((a,b)=>b.ordered_at.localeCompare(a.ordered_at)).slice(0,5))):empty('Comece pela primeira venda','Cadastre um produto e um cliente para registar uma venda.',button('Registar venda','sale-form','','primary'))}</section>`;
  }
  if(view==='sales'){
    const rows=[...state.sales].filter(r=>matches(getCustomer(r.customer_id).name,getProduct(r.product_id).name)&& (filter==='all'||r.status===filter||(filter==='unpaid'&&r.status!=='cancelled'&&dueFor(state,'sale',r)>0))).sort((a,b)=>b.ordered_at.localeCompare(a.ordered_at));
    return `${head('Vendas','Do pedido ao pagamento e à entrega.',button('+ Nova venda','sale-form','','primary'))}<section class="panel">${toolbar(option('all','Todas as vendas')+option('pending','Por entregar')+option('unpaid','Por receber')+option('delivered','Entregues')+option('cancelled','Canceladas'))}${rows.length?table(['Cliente','Produto','Pagamento','Entrega',''],salesRows(rows)):empty('Nenhuma venda encontrada','Registe uma venda ou altere a pesquisa.')}</section>`;
  }
  if(view==='purchases'){
    const rows=[...state.purchases].filter(r=>matches(r.supplier,getProduct(r.product_id).name)&&(filter==='all'||r.status===filter)).sort((a,b)=>b.ordered_at.localeCompare(a.ordered_at));
    return `${head('Encomendas','Acompanhe fornecedores, chegadas e pagamentos.',button('+ Encomenda','purchase-form','','primary'))}<section class="panel">${toolbar(option('all','Todas as encomendas')+option('open','A chegar')+option('received','Recebidas')+option('cancelled','Canceladas'))}${rows.length?table(['Fornecedor / produto','Chegada prevista','Quantidade','Pagamento','Estado',''],rows.map(r=>`<tr><td><strong>${esc(r.supplier)}</strong><span class="sub">${esc(getProduct(r.product_id).name)}</span></td><td>${dateLabel(r.expected_at)}${r.status==='open'&&r.expected_at<today()?`<span class="sub">${badge('Em atraso','red')}</span>`:''}</td><td>${r.received} / ${r.quantity}<span class="sub">unidades recebidas</span></td><td>${money(totalFor(r))}<span class="sub">${r.status==='cancelled'?'Cancelada':`${money(dueFor(state,'purchase',r))} em falta`}</span></td><td>${badge({open:r.received?'Receção parcial':'A chegar',received:'Recebida',cancelled:'Cancelada'}[r.status],r.status==='received'?'green':r.status==='open'?'blue':'')}</td><td>${button('Ver','purchase-detail',r.id,'small')}</td></tr>`)):empty('Nenhuma encomenda encontrada','Registe o pedido ao fornecedor para acompanhar a chegada.')}</section>`;
  }
  if(view==='products'){
    const rows=state.products.filter(r=>matches(r.name,r.sku)&&(filter==='all'||filter==='active'&&r.active||filter==='archived'&&!r.active||filter==='low'&&r.active&&stockFor(state,r.id).available<=r.minimum));
    return `${head('Stock','Disponível = stock físico menos unidades reservadas.',button('+ Produto','product-form','','primary'))}<section class="panel">${toolbar(option('active','Produtos ativos')+option('all','Todos')+option('low','A repor')+option('archived','Arquivados'))}${rows.length?table(['Produto','Stock físico','Reservado','Disponível','Preço / custo','Ações'],rows.map(p=>{const st=stockFor(state,p.id);return `<tr><td><strong>${esc(p.name)}</strong><span class="sub">${esc(p.sku||'Sem referência')} ${!p.active?'· Arquivado':''}</span></td><td>${st.physical}</td><td>${st.reserved}</td><td>${badge(st.available,st.available<=p.minimum?'amber':'green')}<span class="sub">Mínimo ${p.minimum}</span></td><td>${money(p.price_cents)}<span class="sub">Custo ${money(p.cost_cents)}</span></td><td><div class="actions">${button('Editar','product-form',p.id,'small')}${button('Ajustar','adjust',p.id,'small')}${p.active?button('Encomendar','purchase-for',p.id,'small'):''}</div></td></tr>`;})):empty('Nenhum produto encontrado','Cadastre o produto e o stock inicial.')}</section><section class="panel history"><div class="panel-head"><h2>Movimentos recentes</h2><span class="muted small">Receções, entregas e ajustes</span></div>${state.movements.length?table(['Data','Produto','Movimento','Motivo'],[...state.movements].slice(-20).reverse().map(m=>`<tr><td>${dateLabel(m.created_at.slice(0,10))}</td><td>${esc(getProduct(m.product_id).name)}</td><td>${badge((m.quantity>0?'+':'')+m.quantity,m.quantity>0?'green':'amber')}</td><td>${esc(m.note)}</td></tr>`)):empty('Sem movimentos','Os movimentos aparecem quando o stock muda.')}</section>`;
  }
  if(view==='customers'){
    const rows=state.customers.filter(r=>matches(r.name,r.phone)&&(filter==='all'||(filter==='active'?r.active:!r.active)));
    return `${head('Clientes','Contactos e histórico comercial.',button('+ Cliente','customer-form','','primary'))}<section class="panel">${toolbar(option('active','Clientes ativos')+option('all','Todos')+option('archived','Arquivados'))}${rows.length?table(['Cliente','Contacto','Vendas','Por receber',''],rows.map(c=>{const rows=state.sales.filter(r=>r.customer_id===c.id&&r.status!=='cancelled');return `<tr><td><strong>${esc(c.name)}</strong><span class="sub">${c.active?'Ativo':'Arquivado'}</span></td><td>${esc(c.phone||'—')}</td><td>${rows.length}</td><td>${money(rows.reduce((n,r)=>n+dueFor(state,'sale',r),0))}</td><td>${button('Ver cliente','customer-detail',c.id,'small')}</td></tr>`;})):empty('Nenhum cliente encontrado','Adicione um cliente para registar a sua primeira venda.')}</section>`;
  }
  if(view==='followups'){
    const rows=state.sales.filter(r=>r.status==='delivered'&&matches(getCustomer(r.customer_id).name,getProduct(r.product_id).name)&&(filter==='all'||filter==='done'&&r.followup_done||filter==='pending'&&!r.followup_done||filter==='soon'&&!r.followup_done&&daysBetween(today(),r.followup_at)<=state.settings.reminder_days)).sort((a,b)=>a.followup_at.localeCompare(b.followup_at));
    return `${head('Agenda de clientes','Um mês após a entrega, com aviso antecipado.')}<section class="panel">${toolbar(option('pending','Por acompanhar')+option('soon','A contactar agora')+option('all','Todos')+option('done','Concluídos'))}${rows.length?table(['Cliente','Última entrega','Voltar a contactar','Estado','Ações'],followupsRows(rows)):empty('Agenda em dia','Os alertas são criados automaticamente após cada entrega.')}<div class="legend">O sistema mostra os alertas ao abrir a aplicação. Não envia mensagens nem notificações com a aplicação fechada.</div></section>`;
  }
  return `${head('Definições','Preferências, ligação e cópia dos seus registos.')}<div class="setting-grid"><section class="panel"><div class="panel-head"><h2>A sua operação</h2></div><div class="panel-body"><form id="settings-form"><div class="field"><label for="business">Nome da operação</label><input id="business" name="name" value="${esc(state.settings.name)}" maxlength="160" required></div><div class="field"><label for="reminder">Avisar quantos dias antes?</label><input id="reminder" name="reminder_days" type="number" min="0" max="30" value="${state.settings.reminder_days}" required><p class="help">A data de acompanhamento é sempre um mês de calendário após a entrega.</p></div><div class="form-error" role="alert"></div><button class="btn primary" type="submit">Guardar preferências</button></form></div></section><section class="panel"><div class="panel-head"><h2>Conta e dados</h2></div><div class="panel-body"><p><strong>${api.mode==='demo'?'Demonstração local':'Conta sincronizada'}</strong><br><span class="muted small">${esc(api.mode==='demo'?'Dados fictícios neste navegador':api.session?.user?.email||'')}</span></p><div class="settings-note"><p>${api.mode==='demo'?'Entre numa conta online para usar os mesmos registos em vários dispositivos.':'Os registos ficam na sua conta. As alterações aparecem noutros dispositivos em até 20 segundos, enquanto a aplicação estiver aberta.'}</p><p>A versão online precisa de internet para consultar e alterar os registos.</p></div><div class="actions" style="margin-top:20px">${button('Exportar registos','export')}${installPrompt?button('Instalar aplicação','install'):''}${button(api.mode==='demo'?'Sair da demonstração':'Sair da conta','logout')}</div>${api.mode==='demo'?`<div style="margin-top:15px">${button('Repor dados de exemplo','reset-demo','','small danger')}</div>`:''}<p class="help">A exportação é uma cópia JSON para arquivo. Não inclui palavras-passe. Não existe importação automática nesta versão.</p><p class="help">No iPhone: Safari → Partilhar → Adicionar ao ecrã principal.</p></div></section></div>`;
}
function openDialog(title,body,footer='',formId='') {
  modal.innerHTML=`${formId?`<form id="${formId}">`:''}<div class="dialog-head"><h2 id="modal-title">${esc(title)}</h2><button type="button" class="close" aria-label="Fechar" data-action="close">×</button></div><div class="dialog-body">${body}${formId?'<div class="form-error" role="alert"></div>':''}</div>${footer?`<div class="dialog-foot">${footer}</div>`:''}${formId?'</form>':''}`;
  if(!modal.open)modal.showModal();
}
const field=(label,name,value='',type='text',attrs='')=>`<div class="field"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`;
const textfield=(label,name,value='')=>`<div class="field span-2"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" maxlength="1000">${esc(value)}</textarea></div>`;
const choose=(label,name,rows,selected='',blank='Selecione…')=>`<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}" required><option value="">${blank}</option>${rows.map(r=>`<option value="${esc(r.id)}" ${r.id===selected?'selected':''}>${esc(r.label||r.name)}</option>`).join('')}</select></div>`;
const submit=(label='Guardar')=>`${button('Cancelar','close')}<button class="btn primary" type="submit">${label}</button>`;
const hidden=(name,value)=>`<input type="hidden" name="${name}" value="${esc(value||'')}">`;
function formProduct(id){const p=id?getProduct(id):{price_cents:0,cost_cents:0,minimum:5,lead_days:30};openDialog(id?'Editar produto':'Novo produto',`${hidden('id',id)}<div class="form-grid"><div class="span-2">${field('Nome do produto','name',p.name||'','text','required maxlength="160"')}</div>${field('Referência (opcional)','sku',p.sku||'','text','maxlength="60"')}${field('Stock mínimo','minimum',p.minimum,'number','min="0" required step="1"')}${field('Preço de venda (€)','price',(p.price_cents/100).toFixed(2),'text','inputmode="decimal" required')}${field('Custo por unidade (€)','cost',(p.cost_cents/100).toFixed(2),'text','inputmode="decimal" required')}${field('Prazo do fornecedor (dias)','lead_days',p.lead_days,'number','min="0" max="365" required step="1"')}${id?choose('Estado','active',[{id:'true',name:'Ativo'},{id:'false',name:'Arquivado'}],String(p.active)):field('Stock inicial','initial',0,'number','min="0" required step="1"')}</div>`,submit(),'product-form');}
function formCustomer(id){const c=state.customers.find(x=>x.id===id)||{};openDialog(id?'Editar cliente':'Novo cliente',`${hidden('id',id)}${field('Nome do cliente','name',c.name||'','text','required maxlength="160"')}${field('Telefone (opcional)','phone',c.phone||'','tel','maxlength="60"')}${textfield('Observações comerciais (opcional)','note',c.note||'')}${id?choose('Estado','active',[{id:'true',name:'Ativo'},{id:'false',name:'Arquivado'}],String(c.active)):''}`,submit(),'customer-form');}
function formSale(prefill={}) {
  const products=state.products.filter(p=>p.active).map(p=>({...p,label:`${p.name} · ${stockFor(state,p.id).available} disponíveis`}));
  const customers=state.customers.filter(p=>p.active);
  if(!products.length){notify('Cadastre primeiro um produto.');formProduct();return;}
  if(!customers.length){notify('Cadastre primeiro um cliente.');formCustomer();return;}
  openDialog('Nova venda',`<div class="form-grid"><div class="span-2">${choose('Cliente','customer_id',customers,prefill.customer_id)}</div><div class="span-2">${choose('Produto','product_id',products,prefill.product_id)}</div>${field('Quantidade','quantity',prefill.quantity||1,'number','min="1" step="1" required')}${field('Preço por unidade (€)','unit',prefill.unit_cents!==undefined?(prefill.unit_cents/100).toFixed(2):'','text','inputmode="decimal" required')}${field('Data do pedido','ordered_at',today(),'date','required')}${textfield('Observações (opcional)','note')}</div><div id="form-total" class="summary-box">Selecione o produto para calcular o total.</div><div class="field check-field"><label><input type="checkbox" name="allow_backorder"> Pré-encomenda: aceitar pedido mesmo sem stock</label><p class="help">A entrega só será possível quando houver stock físico suficiente.</p></div><p class="help">Registe o pagamento e a entrega nos detalhes da venda.</p>`,submit('Registar venda'),'sale-form');updateTotal();
}
function formPurchase(productId='') {
  const products=state.products.filter(p=>p.active);if(!products.length){notify('Cadastre primeiro um produto.');formProduct();return;}
  const p=products.find(x=>x.id===productId);const expected=new Date();expected.setDate(expected.getDate()+(p?.lead_days||30));const d=`${expected.getFullYear()}-${String(expected.getMonth()+1).padStart(2,'0')}-${String(expected.getDate()).padStart(2,'0')}`;
  openDialog('Encomenda ao fornecedor',`<div class="form-grid"><div class="span-2">${field('Fornecedor','supplier','','text','required maxlength="160"')}</div><div class="span-2">${choose('Produto','product_id',products,productId)}</div>${field('Quantidade','quantity',1,'number','min="1" required step="1"')}${field('Custo por unidade (€)','unit',p?(p.cost_cents/100).toFixed(2):'','text','inputmode="decimal" required')}${field('Data da encomenda','ordered_at',today(),'date','required')}${field('Chegada prevista','expected_at',d,'date','required')}${textfield('Observações (opcional)','note')}</div><div class="summary-box" id="form-total">Selecione o produto para calcular o total.</div>`,submit('Registar encomenda'),'purchase-form');updateTotal();
}
function recordDetail(kind,id) {
  const isSale=kind==='sale',r=state[isSale?'sales':'purchases'].find(x=>x.id===id);if(!r)return;
  const payments=state.payments.filter(x=>x.kind===kind&&x.record_id===id),due=dueFor(state,kind,r);
  const actions=[];
  if(r.status!=='cancelled'&&due>0)actions.push(button(isSale?'Receber pagamento':'Pagar fornecedor','payment',id,'primary',`data-kind="${kind}"`));
  if(isSale&&r.status==='pending')actions.push(button('Confirmar entrega','deliver',id));
  if(!isSale&&r.status==='open')actions.push(button('Registar chegada','receive',id));
  if(r.status!=='cancelled'&&r.status!=='delivered'&&!(r.received||0)&&paidFor(state,kind,id)===0)actions.push(button('Cancelar registo','cancel',id,'danger',`data-kind="${kind}"`));
  openDialog(isSale?'Detalhes da venda':'Detalhes da encomenda',`<div class="details-grid"><div><span>${isSale?'Cliente':'Fornecedor'}</span><strong>${esc(isSale?getCustomer(r.customer_id).name:r.supplier)}</strong></div><div><span>Produto</span><strong>${esc(getProduct(r.product_id).name)}</strong></div><div><span>Quantidade</span><strong>${r.quantity} unidades${!isSale?` · ${r.received} recebidas`:''}</strong></div><div><span>Data do pedido</span><strong>${dateLabel(r.ordered_at)}</strong></div><div><span>Total</span><strong>${money(totalFor(r))}</strong></div><div><span>${isSale?'Recebido':'Pago'}</span><strong>${money(paidFor(state,kind,id))}</strong></div><div><span>Em falta</span><strong>${money(due)}</strong></div><div><span>${isSale?'Entrega':'Chegada prevista'}</span><strong>${isSale?r.status==='cancelled'?'Cancelada':dateLabel(r.delivered_at):dateLabel(r.expected_at)}</strong></div>${isSale&&r.followup_at?`<div><span>Próxima encomenda</span><strong>${dateLabel(r.followup_at)}</strong></div>`:''}</div>${r.note?`<p class="note">${esc(r.note)}</p>`:''}<h3>Pagamentos</h3>${payments.length?payments.map(p=>`<div class="alert-row" style="padding:10px 0"><div><strong>${money(p.amount_cents)}</strong><p>${dateLabel(p.paid_at)} · ${esc(p.method)}</p></div></div>`).join(''):'<p class="muted small">Sem pagamentos registados.</p>'}<div class="actions" style="margin-top:20px">${actions.join('')}</div>`,button('Fechar','close'));
}
function customerDetail(id){const c=getCustomer(id),sales=state.sales.filter(x=>x.customer_id===id);openDialog('Histórico do cliente',`<h3>${esc(c.name)}</h3><p class="muted">${esc(c.phone||'Sem contacto')}</p>${c.note?`<p class="note">${esc(c.note)}</p>`:''}${button('Editar cliente','customer-form',id,'small')}<h3 style="margin-top:23px">Vendas</h3>${sales.length?table(['Data','Produto','Total',''],sales.map(r=>`<tr><td>${dateLabel(r.ordered_at)}</td><td>${esc(getProduct(r.product_id).name)}</td><td>${money(totalFor(r))}</td><td>${button('Ver','sale-detail',r.id,'small')}</td></tr>`)):'<p class="muted small">Sem vendas registadas.</p>'}`,button('Fechar','close'));}
function updateTotal(){const form=$('#sale-form')||$('#purchase-form');if(!form)return;const node=$('#form-total');try{const total=Number(form.elements.quantity.value)*cents(form.elements.unit.value);node.innerHTML=`Total da ${form.getAttribute('id')==='sale-form'?'venda':'encomenda'}<strong>${money(total)}</strong>`;}catch{node.textContent='Preencha a quantidade e o preço para calcular o total.';}}
async function refresh(silent=false){if(!api||busy)return;try{state=await api.snapshot();lastSync=new Date();syncError='';if(!modal.open)shell();}catch(e){syncError=e.message;if(api.mode==='cloud'&&!api.session){api=null;state=emptyState();entry(e.message);}else if(!silent||!modal.open)shell();}}
async function commit(form,kind,payload){
  if(busy)return;busy=true;const controls=[...form.querySelectorAll('button')];controls.forEach(b=>b.disabled=true);const error=form.querySelector('.form-error');error.textContent='';
  try{form.dataset.requestId ||= crypto.randomUUID();state=await api.command(kind,payload,form.dataset.requestId);lastSync=new Date();syncError='';if(modal.open)modal.close();shell();notify('Registo guardado.');}
  catch(e){error.textContent=e.message;if(api.mode==='cloud'&&!api.session){modal.close();api=null;state=emptyState();entry(e.message);}}
  finally{busy=false;controls.forEach(b=>b.disabled=false);}
}
document.addEventListener('submit',async event=>{
  event.preventDefault();const form=event.target;const p=Object.fromEntries(new FormData(form));
  // Um campo name="id" sobrepõe form.id nos formulários HTML.
  const formId=form.getAttribute('id');
  if(formId==='login-form'){
    if(busy)return;busy=true;const b=form.querySelector('button');b.disabled=true;form.querySelector('.form-error').textContent='';
    try{const online=new CloudAPI(config);await online.login(p.email,p.password);const snapshot=await online.snapshot();api=online;state=snapshot;lastSync=new Date();syncError='';shell();}catch(e){form.querySelector('.form-error').textContent=e.message;}finally{busy=false;b.disabled=false;}return;
  }
  if(formId==='connection-form'){
    try{config=validateConfig(p.url.trim(),p.key.trim());localStorage.setItem('fluxo-config-v1',JSON.stringify(config));modal.close();entry();notify('Ligação guardada. Entre na sua conta.');}catch(e){form.querySelector('.form-error').textContent=e.message;}return;
  }
  try{
    let kind=formId.replace('-form','');let payload=p;
    if(kind==='product')payload={id:p.id||null,name:p.name,sku:p.sku,price_cents:cents(p.price),cost_cents:cents(p.cost),minimum:Number(p.minimum),lead_days:Number(p.lead_days),initial:Number(p.initial||0),active:p.active!=='false'};
    if(kind==='customer')payload={...p,id:p.id||null,active:p.active!=='false'};
    if(kind==='sale'||kind==='purchase')payload={...p,quantity:Number(p.quantity),unit_cents:cents(p.unit),allow_backorder:p.allow_backorder==='on'};
    if(kind==='payment')payload={...p,amount_cents:cents(p.amount)};
    if(kind==='receive'||kind==='adjust')payload={...p,quantity:Number(p.quantity)};
    if(kind==='followup')payload={id:p.id,done:p.done==='true'};
    if(kind==='settings')payload={name:p.name,reminder_days:Number(p.reminder_days)};
    await commit(form,kind,payload);
  }catch(e){form.querySelector('.form-error').textContent=e.message;}
});
document.addEventListener('input',event=>{
  if(event.target.id==='search'){const pos=event.target.selectionStart;query=event.target.value;shell();$('#search')?.focus();$('#search')?.setSelectionRange(pos,pos);}
  if(event.target.closest('#sale-form,#purchase-form'))updateTotal();
});
document.addEventListener('change',event=>{
  if(event.target.id==='filter'){filter=event.target.value;shell();}
  if(event.target.name==='product_id'){
    const form=event.target.closest('form'),p=getProduct(event.target.value);if(!p.id)return;
    if(form?.getAttribute('id')==='sale-form')form.elements.unit.value=(p.price_cents/100).toFixed(2);
    if(form?.getAttribute('id')==='purchase-form'){form.elements.unit.value=(p.cost_cents/100).toFixed(2);const date=new Date(form.elements.ordered_at.value+'T12:00:00');date.setDate(date.getDate()+p.lead_days);form.elements.expected_at.value=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
    updateTotal();
  }
});
document.addEventListener('click',async event=>{
  const b=event.target.closest('[data-action]');if(!b||busy)return;const action=b.dataset.action,id=b.dataset.id;
  try{
    switch(action){
      case 'close':modal.close();break;
      case 'demo':api=new DemoAPI();state=await api.snapshot();syncError='';shell();break;
      case 'connection':openDialog('Ligar o sistema online',`${field('URL do projeto Supabase','url',config.supabaseUrl||'','url','required placeholder="https://SEU-PROJETO.supabase.co"')}${textfield('Chave publicável (publishable ou anon)','key',config.publishableKey||'')}<p class="help">Use apenas a chave publicável. A base de dados deve estar preparada com o ficheiro schema.sql incluído no projeto.</p>`,submit('Guardar ligação'),'connection-form');break;
      case 'logout':if(api?.mode==='cloud')await api.logout();api=null;state=emptyState();syncError='';modal.close();entry();break;
      case 'refresh':await refresh();break;
      case 'product-form':formProduct(id);break;
      case 'customer-form':formCustomer(id);break;
      case 'sale-form':formSale();break;
      case 'purchase-form':formPurchase();break;
      case 'purchase-for':formPurchase(id);break;
      case 'sale-detail':recordDetail('sale',id);break;
      case 'purchase-detail':recordDetail('purchase',id);break;
      case 'customer-detail':customerDetail(id);break;
      case 'repeat-sale':{const r=state.sales.find(x=>x.id===id);if(r)formSale(r);break;}
      case 'receive':{const r=state.purchases.find(x=>x.id===id);openDialog('Registar chegada',`${hidden('id',id)}<p>${esc(getProduct(r.product_id).name)} · ${esc(r.supplier)}</p><div class="summary-box">Faltam receber <strong>${r.quantity-r.received} unidades</strong></div>${field('Quantidade recebida agora','quantity',r.quantity-r.received,'number',`required min="1" max="${r.quantity-r.received}" step="1"`)}<p class="help">Pode receber a encomenda em várias partes.</p>`,submit('Confirmar chegada'),'receive-form');break;}
      case 'deliver':{const r=state.sales.find(x=>x.id===id);openDialog('Confirmar entrega',`${hidden('id',id)}<p>${esc(getCustomer(r.customer_id).name)} · ${r.quantity} unidades de ${esc(getProduct(r.product_id).name)}</p>${dueFor(state,'sale',r)>0?`<div class="mode-banner"><p>Esta venda ainda tem ${money(dueFor(state,'sale',r))} por receber. A entrega não regista o pagamento.</p></div>`:''}${field('Data da entrega','delivered_at',today(),'date',`required min="${r.ordered_at}" max="${today()}"`)}<p class="help">As unidades saem do stock e o acompanhamento fica agendado para um mês depois.</p>`,submit('Confirmar entrega'),'deliver-form');break;}
      case 'payment':{const kind=b.dataset.kind,r=state[kind==='sale'?'sales':'purchases'].find(x=>x.id===id);openDialog(kind==='sale'?'Receber pagamento':'Pagar fornecedor',`${hidden('kind',kind)}${hidden('record_id',id)}<div class="summary-box">Valor em falta<strong>${money(dueFor(state,kind,r))}</strong></div>${field('Valor pago agora (€)','amount',(dueFor(state,kind,r)/100).toFixed(2),'text','required inputmode="decimal"')}${field('Data do pagamento','paid_at',today(),'date',`required max="${today()}"`)}${choose('Método','method',[{id:'Transferência',name:'Transferência'},{id:'MB WAY',name:'MB WAY'},{id:'Numerário',name:'Numerário'},{id:'Cartão',name:'Cartão'},{id:'Outro',name:'Outro'}],'Transferência')}<p class="help">Regista um pagamento já realizado. Não processa cobranças bancárias.</p>`,submit('Registar pagamento'),'payment-form');break;}
      case 'cancel':openDialog('Cancelar registo',`${hidden('kind',b.dataset.kind)}${hidden('id',id)}<p>Confirma o cancelamento? O registo fica no histórico.${b.dataset.kind==='sale'?' As unidades reservadas ficam disponíveis.':''}</p>`,submit('Confirmar cancelamento'),'cancel-form');break;
      case 'adjust':{const p=getProduct(id);openDialog('Ajustar stock',`${hidden('product_id',id)}<p>${esc(p.name)}</p><div class="summary-box">Stock físico: ${stockFor(state,id).physical} · reservado: ${stockFor(state,id).reserved}</div>${field('Quantidade a acrescentar ou retirar','quantity','','number','required step="1" placeholder="Ex.: 5 ou -2"')}${field('Motivo','note','','text','required maxlength="160"')}<p class="help">Use um valor positivo para entrada e negativo para saída. Não pode retirar stock reservado.</p>`,submit('Confirmar ajuste'),'adjust-form');break;}
      case 'followup':{const r=state.sales.find(x=>x.id===id);openDialog(r.followup_done?'Reabrir acompanhamento':'Concluir acompanhamento',`${hidden('id',id)}${hidden('done',!r.followup_done)}<p>${r.followup_done?'O acompanhamento volta a aparecer na agenda.':'Marque como concluído depois de acompanhar o cliente. Esta ação não cria uma nova venda.'}</p>`,submit('Confirmar'),'followup-form');break;}
      case 'export':{const data=await api.snapshot();const blob=new Blob([JSON.stringify({format:'fluxo-pro',version:1,exported_at:new Date().toISOString(),mode:api.mode,data},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fluxo-pro-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);notify('Exportação preparada. Guarde o ficheiro num local privado.');break;}
      case 'reset-demo':openDialog('Repor demonstração','<p>Substituir as alterações de demonstração pelos dados de exemplo?</p>',`${button('Cancelar','close')}${button('Repor exemplos','confirm-reset','','danger')}`);break;
      case 'confirm-reset':api.reset();state=await api.snapshot();modal.close();shell();notify('Dados de exemplo repostos.');break;
      case 'install':if(installPrompt){await installPrompt.prompt();installPrompt=null;shell();}break;
      case 'update-app':{const registration=await navigator.serviceWorker.getRegistration();registration?.waiting?.postMessage('SKIP_WAITING');break;}
    }
  }catch(e){notify(e.message);}
});
window.addEventListener('hashchange',()=>{if(!paths[location.hash.slice(1)])return;view=location.hash.slice(1);query='';filter=view==='products'||view==='customers'?'active':view==='followups'?'pending':'all';if(api){shell();window.scrollTo(0,0);}});
window.addEventListener('online',()=>refresh());window.addEventListener('offline',()=>{if(api?.mode==='cloud'){syncError='Sem ligação à internet. Volte a ligar para consultar e guardar os registos.';if(!modal.open)shell();}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh(true);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(api&&view==='settings')shell();});
setInterval(()=>{if(api?.mode==='cloud'&&document.visibilityState==='visible'&&!modal.open)refresh(true);},20000);
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{const ready=()=>{if(reg.waiting)notify('Existe uma atualização. Feche todas as janelas da aplicação e volte a abrir.');};ready();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',ready));}).catch(()=>{});}
async function start(){if(config.supabaseUrl&&config.publishableKey){const online=new CloudAPI(config);if(online.session){api=online;try{state=await api.snapshot();lastSync=new Date();shell();return;}catch(e){api=null;state=emptyState();entry(e.message);return;}}}entry();}
await start();
if(document.modelContext?.registerTool){const controller=new AbortController();window.addEventListener('pagehide',()=>controller.abort(),{once:true});for(const tool of [
  {name:'read_commercial_summary',title:'Consultar resumo comercial',description:'Ler contagens e saldos da conta atualmente aberta.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(!api)throw Error('Entre na conta.');if(Object.keys(input||{}).length)throw Error('Não são aceites parâmetros.');await refresh(true);return {mode:api.mode,products:state.products.length,customers:state.customers.length,pending_deliveries:state.sales.filter(r=>r.status==='pending').length,outstanding_cents:state.sales.filter(r=>r.status!=='cancelled').reduce((n,r)=>n+dueFor(state,'sale',r),0)};}},
  {name:'start_sale_creation',title:'Abrir nova venda',description:'Abrir o formulário de venda. Não guarda nem entrega uma venda.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!api)throw Error('Entre na conta.');if(Object.keys(input||{}).length)throw Error('Não são aceites parâmetros.');formSale();return {opened:true};}}
]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}}
