import test from 'node:test';
import assert from 'node:assert/strict';
import {CloudAPI,validateConfig} from '../docs/api.mjs';
const map=new Map();globalThis.localStorage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};
const config={supabaseUrl:'https://project.supabase.co',publishableKey:'sb_publishable_test'};
test('chaves privilegiadas não podem ser guardadas na aplicação',()=>{assert.throws(()=>validateConfig(config.supabaseUrl,'sb_secret_abc'),/publicável/);const jwt=role=>'eyJx.'+Buffer.from(JSON.stringify({role})).toString('base64url')+'.signature';assert.throws(()=>validateConfig(config.supabaseUrl,jwt('service_role')),/anon/);assert.equal(validateConfig(config.supabaseUrl,jwt('anon')).supabaseUrl,config.supabaseUrl);assert.throws(()=>validateConfig('https://attacker.example',config.publishableKey),/supabase/i);});
test('login, leitura e escrita passam token; request_id é preservado',async()=>{map.clear();const calls=[];globalThis.fetch=async(url,opts)=>{calls.push({url,...opts});const value=url.includes('/auth/')?{access_token:'user-token',refresh_token:'refresh',expires_at:9999999999,user:{email:'example@test.invalid'}}:{products:[],sales:[]};return new Response(JSON.stringify(value),{status:200,headers:{'content-type':'application/json'}});};const api=new CloudAPI(config);await api.login('example@test.invalid','password');await api.snapshot();await api.command('sale',{quantity:1},'request-uuid');assert.equal(calls[1].headers.Authorization,'Bearer user-token');assert.equal(calls[2].headers.apikey,config.publishableKey);assert.equal(JSON.parse(calls[2].body).a.request_id,'request-uuid');assert.equal(calls[2].cache,'no-store');});
test('sem rede a ação falha explicitamente e não afirma guardar localmente',async()=>{globalThis.fetch=async()=>{throw Error('offline');};const api=new CloudAPI(config);api.session={access_token:'token',expires_at:9999999999};await assert.rejects(()=>api.command('receive',{quantity:1}),/não foram alterados/);});
test('token expirado é renovado antes de consultar os registos',async()=>{map.clear();const calls=[];globalThis.fetch=async(url,opts)=>{calls.push(url);return new Response(JSON.stringify(url.includes('refresh_token')?{access_token:'new-token',refresh_token:'new-refresh',expires_at:9999999999}:{products:[]}),{status:200});};const api=new CloudAPI(config);api.session={access_token:'expired',refresh_token:'refresh',expires_at:1};await api.snapshot();assert.match(calls[0],/grant_type=refresh_token/);assert.equal(api.session.access_token,'new-token');});
