import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,applyCommand,stockFor,dueFor,paidFor,addMonth,cents,demoState} from '../docs/domain.mjs';
function fixture(initial=5){let s=emptyState();const run=(k,p,opts={})=>s=applyCommand(s,k,p,{now:'2026-10-03',...opts});run('product',{name:'Caderno',sku:'A',price_cents:850,cost_cents:350,minimum:2,lead_days:30,initial});run('customer',{name:'Cliente',phone:'',note:''});return {get state(){return s;},run,get product(){return s.products[0].id;},get customer(){return s.customers[0].id;}};}
const sale=(f,quantity=2,extra={})=>f.run('sale',{product_id:f.product,customer_id:f.customer,quantity,unit_cents:850,ordered_at:'2026-09-30',...extra});
test('ciclo completo: reserva, pagamento parcial, entrega e acompanhamento mensal',()=>{const f=fixture();sale(f);const id=f.state.sales[0].id;assert.deepEqual(stockFor(f.state,f.product),{physical:5,reserved:2,available:3});f.run('payment',{kind:'sale',record_id:id,amount_cents:500,paid_at:'2026-10-01',method:'MB WAY'});assert.equal(dueFor(f.state,'sale',f.state.sales[0]),1200);f.run('deliver',{id,delivered_at:'2026-10-03'});assert.deepEqual(stockFor(f.state,f.product),{physical:3,reserved:0,available:3});assert.equal(f.state.sales[0].followup_at,'2026-11-03');f.run('payment',{kind:'sale',record_id:id,amount_cents:1200,paid_at:'2026-10-03',method:'Numerário'});assert.equal(dueFor(f.state,'sale',f.state.sales[0]),0);});
test('pré-encomenda sem stock aceita pagamento, mas bloqueia entrega até receção',()=>{const f=fixture(0);assert.throws(()=>sale(f),/insuficiente/);sale(f,2,{allow_backorder:true});const id=f.state.sales[0].id;assert.throws(()=>f.run('deliver',{id,delivered_at:'2026-10-03'}),/insuficiente/);f.run('purchase',{product_id:f.product,supplier:'Fornecedor',quantity:4,unit_cents:350,ordered_at:'2026-10-01',expected_at:'2026-11-01'});f.run('receive',{id:f.state.purchases[0].id,quantity:2});f.run('deliver',{id,delivered_at:'2026-10-03'});assert.equal(stockFor(f.state,f.product).physical,0);});
test('receções parciais não duplicam stock e excedentes são recusados',()=>{const f=fixture(0);f.run('purchase',{product_id:f.product,supplier:'Fornecedor',quantity:10,unit_cents:350,ordered_at:'2026-10-01',expected_at:'2026-11-01'});const id=f.state.purchases[0].id;f.run('receive',{id,quantity:3},{id:'receipt-one'});f.run('receive',{id,quantity:3},{id:'receipt-one'});assert.equal(stockFor(f.state,f.product).physical,3);assert.equal(f.state.purchases[0].status,'open');assert.throws(()=>f.run('receive',{id,quantity:8}),/superior/);f.run('receive',{id,quantity:7});assert.equal(f.state.purchases[0].status,'received');assert.equal(stockFor(f.state,f.product).physical,10);assert.throws(()=>f.run('receive',{id,quantity:1}),/encerrada/);});
test('pagamentos acima do saldo não são registados',()=>{const f=fixture();sale(f);const p={kind:'sale',record_id:f.state.sales[0].id,amount_cents:1701,paid_at:'2026-10-01',method:'Cartão'};assert.throws(()=>f.run('payment',p),/excede/);assert.equal(f.state.payments.length,0);});
test('idempotência evita cobrança registada duas vezes após repetição do pedido',()=>{const f=fixture();sale(f);const p={kind:'sale',record_id:f.state.sales[0].id,amount_cents:500,paid_at:'2026-10-01',method:'Cartão'};f.run('payment',p,{id:'same-request'});f.run('payment',p,{id:'same-request'});assert.equal(paidFor(f.state,'sale',p.record_id),500);});
test('cancelar venda liberta reservas; registos pagos não podem ser cancelados',()=>{const f=fixture();sale(f);const id=f.state.sales[0].id;f.run('cancel',{kind:'sale',id});assert.equal(stockFor(f.state,f.product).available,5);sale(f);const other=f.state.sales[1].id;f.run('payment',{kind:'sale',record_id:other,amount_cents:1,paid_at:'2026-10-01',method:'Outro'});assert.throws(()=>f.run('cancel',{kind:'sale',id:other}),/pagamentos/);});
test('ajustes não retiram unidades reservadas e aumentos são permitidos em pré-encomendas',()=>{const f=fixture();sale(f,4);assert.throws(()=>f.run('adjust',{product_id:f.product,quantity:-2,note:'Inventário'}),/reservado/);f.run('adjust',{product_id:f.product,quantity:-1,note:'Inventário'});assert.equal(stockFor(f.state,f.product).physical,4);const empty=fixture(0);sale(empty,4,{allow_backorder:true});empty.run('adjust',{product_id:empty.product,quantity:1,note:'Inventário'});assert.equal(stockFor(empty.state,empty.product).physical,1);});
test('entrega não pode ser duplicada ou datada no futuro',()=>{const f=fixture();sale(f);const id=f.state.sales[0].id;assert.throws(()=>f.run('deliver',{id,delivered_at:'2026-10-04'}),/entre/);f.run('deliver',{id,delivered_at:'2026-10-03'});assert.throws(()=>f.run('deliver',{id,delivered_at:'2026-10-03'}),/encerrada/);assert.equal(stockFor(f.state,f.product).physical,3);});
test('um mês de calendário ajusta o último dia sem avançar para o mês seguinte',()=>{assert.equal(addMonth('2026-01-31'),'2026-02-28');assert.equal(addMonth('2028-01-31'),'2028-02-29');assert.equal(addMonth('2026-12-31'),'2027-01-31');});
test('valores em euros não acumulam erros de ponto flutuante',()=>{assert.equal(cents('0,10')+cents('0.20'),30);assert.equal(cents('12,34'),1234);for(const v of ['1.234','-1','NaN',''])assert.throws(()=>cents(v));});
test('produtos arquivados conservam histórico e bloqueiam novas vendas',()=>{const f=fixture();const p=f.state.products[0];f.run('product',{...p,active:false});assert.throws(()=>sale(f),/arquivado/);assert.equal(stockFor(f.state,f.product).physical,5);});
test('pagamento ao fornecedor tem saldo separado do cliente',()=>{const f=fixture();f.run('purchase',{product_id:f.product,supplier:'Fornecedor',quantity:5,unit_cents:350,ordered_at:'2026-10-01',expected_at:'2026-11-01'});const r=f.state.purchases[0];f.run('payment',{kind:'purchase',record_id:r.id,amount_cents:750,paid_at:'2026-10-01',method:'Transferência'});assert.equal(dueFor(f.state,'purchase',r),1000);});
test('demonstração mantém stock e pagamentos coerentes',()=>{const s=demoState();assert.equal(s.products.length,3);assert.equal(s.sales.length,2);assert.equal(s.purchases.length,1);assert.equal(stockFor(s,s.products[0].id).physical,22);});
